---
version: 2

before:
  hooks:
    - "go mod tidy"
    - "go generate ./..."

builds:
  - binary: "webhook"
    main: "./main.go"
    env:
      - "CGO_ENABLED=0"
    goarch:
      - "amd64"
      - "arm64"
    goos:
      - "linux"

archives:
  - formats:
      - "tar.gz"
    # this name template makes the OS and Arch compatible with the results of
    # `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

dockers:
  - use: "buildx"
    goarch: "amd64"
    goos: "linux"
    build_flag_templates:
      - "--platform=linux/amd64"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY }}:amd64"
      - "ghcr.io/{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Major }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY }}:{{ . Tag }}-amd64"
  - use: "buildx"
    goarch: "arm64"
    goos: "linux"
    build_flag_templates:
      - "--platform=linux/arm64"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY }}:arm64"
      - "ghcr.io/{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Major }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY }}:{{ . Tag }}-amd64"

docker_manifests:
  - use: "docker"
    name_template: "ghcr.io/{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY }}:latest"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY }}:amd64"
      - "ghcr.io/{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY }}:arm64"
  - use: "docker"
    name_template: "ghcr.io/{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Major }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Major }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Major }}-arm64"
  - use: "docker"
    name_template: "ghcr.io/{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Tag }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Tag }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Tag }}-arm64"

changelog:
  sort: "asc"
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
